### ISSUE TITLE
Jump to definition of symbol 

### ISSUE THREAD

**Issue by adam-singer** [commercialhaskell/intero#231] opened 2016-08-14 20:19 UTC
A feature request, if not already requested, adding support to jump to definition of symbol even if dependency. A nice feature that exists for haskell-vim-now (codex + hasktags) is the ability to have ctags generated for project and dependencies to do navigation. 

Would be nice if that was out of the box support with intero instead of baking up own solution.

**Comment by chrisdone** [comment] 2016-08-16 13:53
I think with `stack haddock` we could hypothetically figure that out. I'd rather not generate tags from source when Haddock already knows how to link up symbols to their source.

**Comment by mgsloan** [comment] 2016-08-16 23:04
Yup, definitely something I'd like to see as well.  Currently stack unpacks source to a temp dir, best solution for this would have it leave the source in a location (read-only?)

**Comment by IvanMalison** [comment] 2016-11-27 06:21
@chrisdone How exactly do you imagine that this would be implemented. This is something that I'd really like to see, and I have some extra time so I'd love to help out however I can.

**Comment by chrisdone** [comment] 2016-11-27 09:26
Intero has the package name and version when you try to jump to definition.

So Intero could run stack unpack on that exact version into .stack/sources
or whatever the correct location is. Then the problem is finding the right
file. GHC might have original file info, might not. This is the key
question mark.

Once you have the file Emacs can jump to it. This will cause Intero to
start another session for that project and load it up too. With the recent
Intero blacklisting support, you could disable that if the projects you're
looking at are large.

That's as far as I got.

**Comment by chrissound** [comment] 2017-08-06 09:09
In the event it is useful: this functionality is present in the intellij plugin: https://github.com/rikvdkleij/intellij-haskell

**Comment by SamuraiJack** [comment] 2017-08-13 20:50
+1 for this feature (already implemented in the IntelliJ plugin)

**Comment by matthew-piziak** [comment] 2017-08-14 02:34
+1

**Comment by georgewsinger** [comment] 2017-09-26 11:23
+1

**Comment by jesuspc** [comment] 2017-10-03 07:03
+1

**Comment by kRITZCREEK** [comment] 2017-10-03 09:22
Stop this. Github introduced the 👍 button for exactly that reason. You're just creating noise.

**Comment by matthew-piziak** [comment] 2017-10-03 14:53
That may be the point. I am not surprised that people _really want_ basic navigation.

**Comment by matthew-piziak** [comment] 2017-10-03 15:00
@chrisdone I'm guessing this is marked as `priority: low` because of blocking difficulties (https://github.com/commercialhaskell/intero/issues/231#issuecomment-263111676) and not because the feature is not deemed important, is that right? Are there any new developments since last year that might make this more possible now?

**Comment by mgsloan** [comment] 2017-10-03 23:49
I don't think there are new developments here.  This is actually quite an involved feature to implement.  Don't let that dissuade y'all, though.  If someone wants to implement this, it'd be greatly appreciated by everyone!

**Comment by matthew-piziak** [comment] 2017-10-04 01:55
Thanks @mgsloan! I don't mean to understate the difficulty of course. :)

**Comment by yilinwei** [comment] 2017-10-28 20:39
@chrisdone I've been taking a look at this at the same time as #129 and was wondering whether you knew of a better way that going to the using haddock generated html files to get the line info?

Would that still be an acceptable way of doing it?

**Comment by mgsloan** [comment] 2017-10-29 00:34
@yilinwei It may also be worthwhile investigating if the .hi files have the requisite info, I'm not sure if they do, but perhaps they should!

Last resort would be to run intero on every dependency and output a metadata file.  Could get tricky for running it on builtin libraries.  This could be useful for other reasons, though.  Some info definitely isn't in .hi files, such as "find usages".  Imagine if you could use "find usages" to find all usages of an identifier in your dependencies, possibly all usages in the entire stackage snapshot.  This would be really powerful!  I feel like I've written something about this before, but can't find it easily with a search of this repo's issues.

Could even consider distributing these metadata files, but that is frought with problems because they may depend on selection of flags, may even depend on dependencies.  Due to TH, could depend on practically anything.

**Comment by IvanMalison** [comment] 2017-10-29 01:09
> @yilinwei It may also be worthwhile investigating if the .hi files have the requisite info, I'm not sure if they do, but perhaps they should!

I'm pretty sure that they don't, but I agree that they should. It wouldn't be hard to make a change to ghc to add this would it?

**Comment by mgsloan** [comment] 2017-10-29 03:12
> It wouldn't be hard to make a change to ghc to add this would it?

Probably not!  Likely worthwhile.  It'd probably be good to add support to ghci / intero as part of that, as it might be hard to get it merged without a concrete application.

**Comment by androidfred** [comment] 2017-12-10 11:20
Lack of go to definition is a show-stopper for a lot of people. What's preventing Intero from using a similar implementation to the IntelliJ-Haskell plugin?

**Closed** 2019-01-03 14:42 UTC
Labels: component: emacs, priority: low, type: enhancement

**Comment by jvliwanag** [comment] 2019-01-04 14:33
My emacs-fu isn't too great, but in case it's useful, I've got a workable `M-.`. I have both haskell-mode and intero set-up, and on a project I'm working on, I run a `codex update`.

I bind `M-.` to:

```
(defun intero-goto-or-haskell-jump ()
    "Intero goto or haskell jump."
    (interactive)
    (let ((d (intero-goto-definition)))
      (when (sequencep d) (haskell-mode-jump-to-def-or-tag))))
```

This attempts the intero way first, and on failure, tries haskell-mode's lookup through tags.

**Comment by ntc2** [comment] 2019-01-08 19:39
@jvliwanag thanks, that's a huge improvement! I further extended your command to support a prefix argument, in which case it runs `xref-find-definitions` (which prompts for an identifier with completions from the `TAGS`). Here's [the complete setup](https://github.com/ntc2/conf/blob/44e952c972bb94fd02f4b89e92e9824116a7d4e1/dot.emacs.d/extensions/haskell.el#L322), simplified:

```elisp
(defun my-haskell-mode-hooks ()
  (define-key intero-mode-map (kbd "M-.") 'intero-goto-or-haskell-jump-or-tag))

(defun intero-goto-or-haskell-jump-or-tag (&optional prefix)
    "Try Intero goto, then Haskell Mode goto, then tags jump."
    (interactive "P")
    (if (not prefix)
        (let ((d (intero-goto-definition)))
          (when (sequencep d) (haskell-mode-jump-to-def-or-tag)))
      (call-interactively 'xref-find-definitions)))

(add-hook 'haskell-mode-hook 'my-haskell-mode-hooks)
```
