### ISSUE TITLE
Intero REPL builds instead of interprets files

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#230] opened 2016-08-13 20:55 UTC
When using intero's REPL, files are always compiled. If I `:load` a module with the same options, instead, they are loaded as interpreted, which takes less time. `:set -fbyte-code` improves that.

A log demonstrating the compilation:
```
Starting:
  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero11129vMd --ghci-options -hidir=/var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero11129vMd stack
Intero 0.1.16 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

 [ 1 of 65] Compiling System.Process.Log ( /Users/pgiarrusso/AeroFS/Repos/stack-bluevelvet/src/System/Process/Log.hs, /var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero11129vMd/System/Process/Log.o )
[ 2 of 65] Compiling Text.PrettyPrint.Leijen.Extended ( /Users/pgiarrusso/AeroFS/Repos/stack-bluevelvet/src/Text/PrettyPrint/Leijen/Extended.hs, /var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero11129vMd/Text/PrettyPrint/Leijen/Extended.o )
[... continues building all files]
```

**Comment by karljs** [comment] 2016-08-13 21:43
This is closely related to #191 I think, just with a different motivation.  I've been following that issue hoping will be patched soon.

**Comment by chrisdone** [comment] 2016-08-16 12:28
Closing as dupe of #171. :+1:

**Closed by chrisdone** 2016-08-16 12:28 UTC
