### ISSUE TITLE
Restarting Intero does not restart repl

### ISSUE THREAD

**Issue by ntc2** [commercialhaskell/intero#269] opened 2016-09-22 21:27 UTC
After killing my Intero repl with `C-c C-c` -- my `:main` was loopy -- I tried to reload with `M-x intero-repl-load`, which failed with 

> Buffer *intero:<pkg>:<target>:repl* has no process.

I tried `M-x intero-restart` and `M-x intero-destroy`, but `M-x intero-repl-load` continued to fail in the same way. Eventually I discovered that killing the Intero repl buffer and then running `M-x intero-repl-load` got me a new repl.

It would be better if `M-x intero-repl-load` started a new repl when the Intero repl buffer has no process.

**Comment by chrisdone** [comment] 2016-09-28 08:17
Closing as dupe of #120. Please hit Subscribe on that issue, so that when it's fixed you'll get the notification.

**Closed by chrisdone** 2016-09-28 08:17 UTC
