### ISSUE TITLE
candidates missing from company completion

### ISSUE THREAD

**Issue by unthingable** [commercialhaskell/intero#136] opened 2016-07-04 17:29 UTC
![screen shot 2016-07-04 at 10 21 04](https://cloud.githubusercontent.com/assets/925755/16567266/65385134-41d1-11e6-9035-7f1dbbeea405.png)

`applyAsTemplate` is defined in the same module as `applyTemplate`, but missing from candidates. Similar to #115, it seems.

Also if that helps, starting intero REPL hangs at:

```
Ok, modules loaded: Main.
Collecting type info for 1 module(s) ...
?
```

**Comment by chrisdone** [comment] 2016-07-06 09:07
Duplicate of #115. Please subscribe to the notifications of #115 for update fixes. 👍

**Closed by chrisdone** 2016-07-06 09:07 UTC
