### ISSUE TITLE
Load files without .hs extension to repl

### ISSUE THREAD

**Issue by rgrinberg** [commercialhaskell/intero#437] opened 2017-07-01 11:19 UTC
For example, If I'm using stack's script functionality then I'd like to omit the .hs extension from my scripts. But then intero refuses to load my scripts to ghci. Would be nice if this limitation was lifted.

**Comment by KarlFish** [comment] 2017-07-08 01:25
Duplicates https://github.com/commercialhaskell/intero/issues/80, which is also unsolved.

**Comment by purcell** [comment] 2017-07-09 06:06
Yep, closing as duplicate of #80.

**Closed by purcell** 2017-07-09 06:06 UTC
