### ISSUE TITLE
Repl runs intero main instead of defined main

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/intero#317] opened 2016-11-21 17:37 UTC
```
So now, I'm fiddling around with intero in emacs, trying to play with the repl, etc.  Here, I'm running into questions:

1.  I believe I should be able to load my main module with :load Main.  This seems to work...I get the following message from the repl:
    Ok, modules loaded: Main.
    Collecting type info for 1 module(s) ... 
After that, shouldn't I be able to execute my 'main' function from the repl?  I try to and get the following:
    > main
    Too late for parseStaticFlags: call it before runGhc or runGhcT
    *** Exception: ExitFailure 1

Any intero users that know what's going on here?
```

https://www.reddit.com/r/haskell/comments/5dzilp/gettting_started_with_haskell_stack_interoemacs/

**Comment by CarstenKoenig** [comment] 2016-11-21 17:48
as you asked for feedback on the Reddit Thread - I just tried (Intero 0.1.18, Ghc 8.0.1) with

```haskell
module Test where

main :: IO ()
main = putStrLn "Hello"
```

and both `:main` and `main` are working as expected - maybe you can add your module/main (slim it down as much as you can) so we can try to reproduce?

Also the debug output (`M-x intero-toggle-debug` - look at the `*Messages*` buffer afterward) can probably help here.

**Comment by chrisdone** [comment] 2016-11-23 14:00
Closing as dupe of #114. Please subscribe to that issue! 👍

**Closed by chrisdone** 2016-11-23 14:00 UTC
Labels: component: intero, type: bug
