### ISSUE TITLE
how to get ghci history to persist across sessions

### ISSUE THREAD

**Issue by gremdrus** [commercialhaskell/intero#457] opened 2017-08-08 20:01 UTC
I cannot seem to get ghci/intero repl to persist across sessions, nothing is being written to ~/.ghc/ghci_history.

**Comment by unhammer** [comment] 2017-08-31 08:53
https://github.com/commercialhaskell/intero/issues/224 related?

**Comment by chrisdone** [comment] 2017-09-06 23:07
Dupe of #224.

**Closed by chrisdone** 2017-09-06 23:07 UTC
