### ISSUE TITLE
Show type in autocomplete suggestions. 

### ISSUE THREAD

**Issue by Tombert** [commercialhaskell/intero#354] opened 2017-01-12 22:18 UTC
Hello!
I really enjoy the intero plugin, but have become slightly spoiled by the FSharp support for emacs.  

When doing autocomplete, it gives me the type and a description if it's available. 
![screen shot 2017-01-12 at 5 14 50 pm](https://cloud.githubusercontent.com/assets/2027925/21910603/bf5a6b1a-d8ea-11e6-839b-4db875bae745.png)

Is there an option to have the autocomplete talk to Hoogle or something to grab the type and mimic this feature? 

I'd be happy to add this myself, if someone would point me in the right direction to get started.

**Comment by tepf** [comment] 2017-01-25 09:31
Maybe  this could be combined with automatically showing the type signature in the bottom, of the function you just completed. Imagine you complete `fun1 :: [Int] -> Text` and after you typed `fun1` and are about to insert the arguments the signature will be shown in the bottom as a reference while you're typing out the arguments.

**Comment by chrisdone** [comment] 2017-01-25 10:40
Closing as duplicate of #71. See that issue and I'll write a comment on it for how to get started implementing this.

**Closed by chrisdone** 2017-01-25 10:40 UTC
