### ISSUE TITLE
`intero-goto-definition` jumps to a random mirrored file (e.g. `intero20106PWR.hs`)

### ISSUE THREAD

**Issue by sboosali** [commercialhaskell/intero#348] opened 2017-01-02 22:02 UTC
Then, when I accidentally edit it (when I'm in the middle of work and jump to the definition, I don't double check that the file is some strange temporary file), and then jump back to edit the original file `Example.hs` and save, it prompts me that the other file (`intero20106PWR.hs`) has changed on disk. 

I'm on Emacs25 and nix, if that matters. 

This check might be relevant, but it seems fine:

https://github.com/commercialhaskell/intero/blob/948ae6bef9c0fb120c2cceab70c7bcc323b55940/elisp/intero.el#L361

**Comment by chrisdone** [comment] 2017-01-03 11:06
Oh, I've managed to get a reproduction case for this:

1. Edit file A and B where A imports B.
2. Edit B.
3. Edit A.
4. Now in a jump to a definition that comes from B. It jumps to the temp file.

That'll be because the GHC API has already loaded in B via a temp file earlier (all checked files are checked via a temp file), so it doesn't reload the B filename when checking the A module.

So we can just do a check upon receiving the filename: is this a temp file path? If so, map it back to the proper filename.

**Comment by chrisdone** [comment] 2017-01-03 11:43
@purcell I pushed some commits on this, mind taking a quick look?

@sboosali I pushed a fix, can you try it? I no longer reproduce the issue. Thanks for reporting!

**Closed by chrisdone** 2017-01-03 11:43 UTC
Labels: component: emacs, priority: high, type: bug

**Comment by sboosali** [comment] 2017-01-03 20:59
It works, thanks for the quick fix!!

**Comment by purcell** [comment] 2017-01-05 06:23
Nice.
